config/routes.rb
DominoExp::Application.routes.draw do
 

resources :users do
  resources :dominos
end

resources :logs  

  get "users/new"

  get "welcome/index"
  
  get "welcome/log"

  get "welcome/track"

  get "welcome/request"

  get "welcome/about"

  get "welcome/faq"

  get "welcome/contact"

  get "welcome/donate"

  get "welcome/legal"

  root :to => 'welcome#index'

  match '/signup',  to: 'users#new'

end

app/models/domino.rb
class Domino < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :users
  has_many :logs, :dependent => :destroy
end

app/models/log.rb
class Log < ActiveRecord::Base
  attr_accessible :body, :date, :location
  belongs_to :user
  belongs_to :domino
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :pword
  #added this line
  has_and_belongs_to_many :dominos
  has_many :logs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  
end

app/controllers/dominos_controller.rb
class DominosController < ApplicationController

#create
#show
#destroy
#update


def create
    @user = User.find(params[:user_id])
    @domino = @user.dominos.create(params[:domino])
  end


def show
		@user = User.find(params[:user_id])
		@domino = @user.dominos.find(params[:id])
end

def destroy
    @user = User.find(params[:user_id])
    @domino = @user.dominos.create(params[:domino])
    @domino.destroy
  end

def index
		@user = User.find(params[:user_id])
		@dominos = @user.dominos.all
end


end

app/controllers/logs_controller.rb
class LogsController < ApplicationController

#create
#show
#destroy

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
    	@user = User.new(params[:user_id])
  	end

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  #def log
  #end

  #def track
  #end

  #def request
  #end

  #def about
  #end

  #def faq
  #end

  #def contact
  #end

  #def donate
  #end

  #def legal
  #end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dominos_helper.rb
module DominosHelper
end

app/helpers/log_helper.rb
module LogHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dominos/index.html.erb
<% @dominos.each do |domino| %>
	
	<%= link_to domino.name, [@user, domino] %>
	
	<% end %>

app/views/dominos/show.html.erb
<table border = "1">

<tr>
	<th>Activated:</th>
	<td>12/02/12</td>
</tr>

<tr>
	<th>I logged:</th>
	<td>05/16/13</td>
</tr>

<tr>
	<th>Logs since me:</th>
	<td>7</td>
</tr>

<tr>
	<th>Days since last log:</th>
	<td>8</td>
</tr>

<tr>
	<th>Card status:</th>
	<td>Very active</td>
</tr>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,200italic,400italic' rel='stylesheet' type='text/css'>

  	<title>The Domino Experiment</title>
  		<%= stylesheet_link_tag    "application", :media => "all" %>
  		<%= javascript_include_tag "application" %>
  		<%= csrf_meta_tags %>
</head>

<body>

	<header>

	<div class="navbar navbar-fixed-top navbar-inverse">

		<div class="navbar-inner">
			<ul class="nav pull-left">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", welcome_about_path %></li>
				<li><%= link_to "Contact", welcome_contact_path %></li>	
			</ul>	
			
		</div>
	</div>

	</header>

<%= yield %>





</body>
</html>

app/views/users/create.html.erb
<h1> Create a new user </h1>

<%= form_for @user do |f| %>
	<p>
		<%= f.label :username %>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :password %>
		<%= f.text_field :pword %>
	</p>

	<p>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</p>

	<p>
		<%= f.submit "Create" %>
	</p>

<% end %>

app/views/users/edit.html.erb
<h1> Create a new user </h1>

<%= form_for @user do |f| %>
	<p>
		<%= f.label :username %>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :password %>
		<%= f.text_field :pword %>
	</p>

	<p>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</p>

	<p>
		<%= f.submit "Update" %>
	</p>

<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
	
	<span><%= link_to user.name, user %></span>	
	<%= pluralize(user.dominos.count, 'domino')%>

	<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% plural = @user.dominos.count == 1 ? "" : "s"%>  

<%if @user.dominos.count == 0%>
	
	You don't have any dominos yet. Request one <%= link_to "here", welcome_request_path %>!

<%else%>
	<%= @user.name %>'s Domino<%= plural %>:

	<% @user.dominos.each do |domino| %>
	<%= link_to domino.name, [@user, domino] %>
	<% end %> 

<%end%>	

app/views/welcome/about.html.erb
<h3>About</h3>
<h4>The domino experiment is an experiment in kindess</h4>

app/views/welcome/contact.html.erb
<h1>Contact</h1>
<h3>kyle@dominoexperiment.com</h3>

app/views/welcome/donate.html.erb
<h2>Donate</h2>
<h3>Monay</h3>

app/views/welcome/faq.html.erb
<h1>FAQ</h1>
<h3>Got questions for us?</h3>

app/views/welcome/index.html.erb
<div id="banner">		
		<img src="assets/headerlogo.png"/>
	</div>

<h2>track the impact of your random acts of kindness</h2>




	
			<div class="span4">
				<h3>have a domino?</h3>
				<h4>enter your code to the right and track all of the good your domino does because you passed it on</h4>
			</div>
			



	<div class="row-fluid">
		
		<div class="span4">
			<div class = "shadow">
				<img src="assets/domino.png" style="height:200px"/>
			</div>
			<div class="arrow">
				<img src="assets/arrow.png"/>
			</div>
		</div>

		
		

		

	<div class="spacer2">

		<div class="row-fluid">
			
<div class="span4">
			<div id ="inputappendwrap">
	  			<div class="input-append">
	  				<input id="appendedInputButton" style="width:80px" placeholder='XTRZ6541' maxlength="8" type="text">
	  				<div id ="buttonwrap">
	  					<button class="btn" type="button">Log & Track!</button>
	  				</div>
				</div>
			</div>

	</div>

			
	</div>
</div>

app/views/welcome/legal.html.erb
<h1>Legal</h1>
<h3>Privacy blah blah blah</h3>

app/views/welcome/log.html.erb
<h1>Log</h1>
<h2>your domino-receiving experience</h2>

<%= text_area_tag(:message, "Soo...what happened?", :size => "24x6") %>

app/views/welcome/request.html.erb
<h2>Request</h2>
<h3>Gimme one dem dominoes, boy</h3>

app/views/welcome/track.html.erb
<h2>Track</h2>
<h3>In order to track dominos, you'll need to create an account or sign in</h3>